#!/bin/bash

echo "🚀 GitHub Repository Setup for ClearComply"
echo "========================================="
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}Current Git Status:${NC}"
git status --porcelain

echo ""
echo -e "${YELLOW}📋 Next Steps to Create GitHub Repository:${NC}"
echo ""
echo "1️⃣  Go to GitHub.com and create a new repository:"
echo "   🌐 https://github.com/new"
echo ""
echo "2️⃣  Repository Settings:"
echo "   📝 Repository name: clearcomply-assessment-platform"
echo "   📖 Description: Full-stack compliance assessment platform with NIST 800-53 support"
echo "   🔓 Visibility: Public (or Private if preferred)"
echo "   ❌ Do NOT initialize with README, .gitignore, or license (we already have these)"
echo ""
echo "3️⃣  After creating the repository, run these commands:"
echo ""
echo -e "${GREEN}   # Add the remote repository (replace YOUR-USERNAME)${NC}"
echo "   git remote add origin https://github.com/YOUR-USERNAME/clearcomply-assessment-platform.git"
echo ""
echo -e "${GREEN}   # Push the code to GitHub${NC}"
echo "   git push -u origin main"
echo ""
echo "📊 Repository Statistics:"
echo "========================"
echo "Files: $(git ls-files | wc -l | tr -d ' ') files"
echo "Lines of code: $(git ls-files | xargs wc -l | tail -1 | awk '{print $1}') lines"
echo "Commit: $(git rev-parse --short HEAD)"
echo ""

echo -e "${BLUE}📁 Project Structure Summary:${NC}"
echo ""
echo "ClearComply/"
echo "├── 🔧 Service/                   # FastAPI Backend"
echo "│   ├── app/                      # Application code"
echo "│   │   ├── models.py             # Data models & validation"
echo "│   │   ├── routes.py             # API endpoints"
echo "│   │   └── data_store.py         # Data management"
echo "│   ├── data/                     # Framework data"
echo "│   └── main.py                   # Application entry"
echo "├── 🎨 UI/                        # React Frontend"
echo "│   ├── src/components/           # React components"
echo "│   ├── src/services/             # API integration"
echo "│   └── package.json              # Dependencies"
echo "├── 🐳 docker-compose.yml         # Container orchestration"
echo "├── 🛠️  dev.sh                    # Development server"
echo "└── 📋 README-COMPLETE.md         # Comprehensive documentation"
echo ""

echo -e "${YELLOW}🎯 Key Features in Repository:${NC}"
echo "✅ Complete full-stack application"
echo "✅ NIST 800-53 compliance framework"
echo "✅ Interactive question answering"
echo "✅ Real-time progress tracking"
echo "✅ Material UI design system"
echo "✅ Docker containerization"
echo "✅ Comprehensive documentation"
echo "✅ Testing scripts included"
echo "✅ TypeScript for type safety"
echo "✅ CORS-enabled API"
echo ""

echo -e "${GREEN}🎉 Ready to push to GitHub!${NC}"
echo ""
echo "💡 Pro Tips:"
echo "• Add repository topics: fastapi, react, typescript, compliance, nist-800-53"
echo "• Enable GitHub Pages for documentation"
echo "• Set up GitHub Actions for CI/CD"
echo "• Add issue templates for bug reports and features"
echo ""

echo -e "${BLUE}📞 Support:${NC}"
echo "After pushing, your repository will be available at:"
echo "https://github.com/YOUR-USERNAME/clearcomply-assessment-platform"
