"""phase2_state_history_csf_profile_extended_answers

Revision ID: 10a9d3a9cc19
Revises: 7fe96183ae7f
Create Date: 2026-05-17 21:42:40.327994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10a9d3a9cc19'
down_revision: Union[str, Sequence[str], None] = '7fe96183ae7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_state_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('assessment_id', sa.String(), nullable=False),
    sa.Column('from_status', sa.String(), nullable=True),
    sa.Column('to_status', sa.String(), nullable=False),
    sa.Column('changed_by_email', sa.String(), nullable=True),
    sa.Column('changed_by_name', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_state_history_assessment_id'), 'assessment_state_history', ['assessment_id'], unique=False)
    op.create_table('csf_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('assessment_id', sa.String(), nullable=False),
    sa.Column('function_id', sa.String(), nullable=False),
    sa.Column('function_name', sa.String(), nullable=True),
    sa.Column('current_tier', sa.Integer(), nullable=False),
    sa.Column('target_tier', sa.Integer(), nullable=False),
    sa.Column('gap_description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_csf_profiles_assessment_id'), 'csf_profiles', ['assessment_id'], unique=False)
    op.add_column('answers', sa.Column('implementation_status', sa.String(), nullable=True))
    op.add_column('answers', sa.Column('implementation_description', sa.Text(), nullable=True))
    op.add_column('answers', sa.Column('responsible_role', sa.String(), nullable=True))
    op.add_column('answers', sa.Column('assessment_methods', sa.Text(), nullable=True))
    op.add_column('answers', sa.Column('inherited', sa.Boolean(), nullable=False))
    op.add_column('answers', sa.Column('inherited_from', sa.String(), nullable=True))
    op.add_column('answers', sa.Column('design_effectiveness', sa.String(), nullable=True))
    op.add_column('answers', sa.Column('operating_effectiveness', sa.String(), nullable=True))
    op.add_column('answers', sa.Column('current_tier', sa.Integer(), nullable=True))
    op.add_column('answers', sa.Column('target_tier', sa.Integer(), nullable=True))
    op.add_column('answers', sa.Column('internal_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'internal_notes')
    op.drop_column('answers', 'target_tier')
    op.drop_column('answers', 'current_tier')
    op.drop_column('answers', 'operating_effectiveness')
    op.drop_column('answers', 'design_effectiveness')
    op.drop_column('answers', 'inherited_from')
    op.drop_column('answers', 'inherited')
    op.drop_column('answers', 'assessment_methods')
    op.drop_column('answers', 'responsible_role')
    op.drop_column('answers', 'implementation_description')
    op.drop_column('answers', 'implementation_status')
    op.drop_index(op.f('ix_csf_profiles_assessment_id'), table_name='csf_profiles')
    op.drop_table('csf_profiles')
    op.drop_index(op.f('ix_assessment_state_history_assessment_id'), table_name='assessment_state_history')
    op.drop_table('assessment_state_history')
    # ### end Alembic commands ###
