"""add_assessment_type_column

Revision ID: 2d71cd6ab67f
Revises: 600d790ff8ec
Create Date: 2026-07-28 20:28:55.946539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d71cd6ab67f'
down_revision: Union[str, Sequence[str], None] = '600d790ff8ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessments', sa.Column('assessment_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessments', 'assessment_type')
    # ### end Alembic commands ###
