"""add_diagram_columns_to_assessment

Revision ID: 3bed3d66fa53
Revises: 3fccaaa686dd
Create Date: 2026-06-29 22:52:33.133786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bed3d66fa53'
down_revision: Union[str, Sequence[str], None] = '3fccaaa686dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessments', sa.Column('diagram_filename', sa.String(), nullable=True))
    op.add_column('assessments', sa.Column('diagram_storage_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessments', 'diagram_storage_path')
    op.drop_column('assessments', 'diagram_filename')
    # ### end Alembic commands ###
