"""add_ssp_builder_tables

Revision ID: 3fccaaa686dd
Revises: a2d0812fd382
Create Date: 2026-06-29 22:00:51.308659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fccaaa686dd'
down_revision: Union[str, Sequence[str], None] = 'a2d0812fd382'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ssp_checklist',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('assessment_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('target_link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ssp_checklist_assessment_id'), 'ssp_checklist', ['assessment_id'], unique=False)
    op.create_table('ssp_intake_teams',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('assessment_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lead_name', sa.String(), nullable=False),
    sa.Column('lead_email', sa.String(), nullable=False),
    sa.Column('response_rate', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_active_days_ago', sa.Integer(), nullable=False),
    sa.Column('families', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ssp_intake_teams_assessment_id'), 'ssp_intake_teams', ['assessment_id'], unique=False)
    op.create_table('ssp_inventory_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('assessment_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ssp_inventory_items_assessment_id'), 'ssp_inventory_items', ['assessment_id'], unique=False)
    op.create_table('ssp_risk_questions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('assessment_id', sa.String(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('mapped_control', sa.String(), nullable=True),
    sa.Column('response', sa.String(), nullable=False),
    sa.Column('points_missed', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ssp_risk_questions_assessment_id'), 'ssp_risk_questions', ['assessment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ssp_risk_questions_assessment_id'), table_name='ssp_risk_questions')
    op.drop_table('ssp_risk_questions')
    op.drop_index(op.f('ix_ssp_inventory_items_assessment_id'), table_name='ssp_inventory_items')
    op.drop_table('ssp_inventory_items')
    op.drop_index(op.f('ix_ssp_intake_teams_assessment_id'), table_name='ssp_intake_teams')
    op.drop_table('ssp_intake_teams')
    op.drop_index(op.f('ix_ssp_checklist_assessment_id'), table_name='ssp_checklist')
    op.drop_table('ssp_checklist')
    # ### end Alembic commands ###

